import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

/**
 * A redux toolkit API slice that is used to fetch the Person data. The getPeople endpoint
 * is used by the ListPanel.
 */
export const personApiSlice = createApi({
    reducerPath: 'personApi',
    baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:8080/api/people' }),
    endpoints: (builder) => ({

        getPeople: builder.query({
            query: () => `/`
        })
    }),
});

// Hooks are automatically generated by redux toolkit based on the endpoint names
export const { useGetPeopleQuery } = personApiSlice;