import { createSlice } from '@reduxjs/toolkit';
import { Player, PlayerState } from 'utils/types';

const initialPlayerState: PlayerState = {
    currentPlayer: Player.O
};

const playerSlice = createSlice({
    name: 'player',
    initialState: initialPlayerState,
    reducers: {
        currentPlayerChanged: (state, { payload }) => {
            state.currentPlayer = payload;
        }
    }
});

// Redux actions automatically generated by redux toolkit based on the reducer names
export const { currentPlayerChanged } = playerSlice.actions;

export default playerSlice;